\c cacti_dev;

INSERT INTO cacti(name, image, scientific_name, origin, life_expectancy, flowers, max_height, fun_fact, care_instructions, edible) VALUES 
('Prickly Pear (aka nopal)', 'https://www.bhg.com/thmb/Dw1HcTAnYc03r1rEZuJVYT9BerQ=/1244x0/filters:no_upscale():strip_icc()/spineless-prickly-pear-47685be1-64f0a05562a342bfa6d1dc834a821557.jpg',  'Opuntia', 'Western Hemisphere', 20, true, '15 feet', 'The red fruit or pear of this cactus are also known as "tuna".', 'Water whenever the compost has dried out, allowing any excess to drain away. Feed with a cactus fertiliser once every two months from spring to early autumn. In winter, move to a cooler spot to encourage flowers. Repot young plants every spring, and mature plants every couple of years.', true),
('Moon', 'https://cdn11.bigcommerce.com/s-oqm1pc/images/stencil/1280x1280/products/4260/15039/red_graft2__30309.1655327193.jpg', 'Gymnocalycium mihanovichii', 'Argentina', 5, false, '1 foot', 'This cute “mutant”, Moon Cactus, is actually a combination of two cacti, typically Gymnocalycium (the sicon) and a rootstock cactus.', 'Provide the appropriate balance of light and shade. The rootstock cactus must receive enough sunlight for photosynthesis. Position your moon cactus near a window, but ensure that it only receives partial sunlight, as bright light can be damaging. If you decide to place your cactus on a windowsill, ensure that blinds protect it from receiving too much direct sunlight.', false),
('Fairy Castle', 'https://www.sublimesucculents.com/wp-content/uploads/2021/01/fairy-castle-cactus-in-black-pot.jpg', 'Acanthocereus tetragonus', 'North, Central, and South America', 10, false, '6 feet', 'The Fairy Castle Cactus is often sold with large bright flowers, but take a closer look - these are actually frequently fake flowers that have been glued onto the stems! They wont harm your plant, so you can just leave them be as theyll eventually fall off as your cactus grows.', 'Ensure the fairy castle cactus receives plenty of light. Fairy castle cacti kept as house plants should be grown in a space that receives lots of sunlight. If these plants do not receive enough light, the colors will fade and their columns will become misshapen. This is a full-sun plant, but it will survive in partial shade.', true ),
('Christmas', 'https://publish.purewow.net/wp-content/uploads/sites/2/2022/10/Holiday-Cactus-Hero.jpg', 'Schlumbergera bridgesii', 'coastal mountains of southeastern Brazil', 20, true, '4 feet', 'While its scientific name is Schlumbergera bridgesii (try saying that five times fast), it’s also known as a Thanksgiving cactus, Easter cactus, and orchid cactus.', 'For successful growth indoors, choose a well-draining potting soil containing perlite and a container with good drainage holes. Christmas cacti are sensitive to root rot. Avoid overwatering the plants, and do not let water sit in the saucer beneath containers. Water plants when the soil is dry to the touch.', false),
('Saguaro', 'https://dbg.org/wp-content/uploads/2022/04/header.jpg', 'Carnegiea gigantea', 'Sonoran Desert', 150, true, '40 feet', 'Most of the saguaros roots are only 4-6 inches deep and radiate out as far from the plant as it is tall.', 'The saguaro cactus is a desert plant that doesnt need to be connected to drip irrigation. However, they do benefit from some supplemental water during periods of drought. The best way to water your saguaro is to make a tree well around the base of the plant and run a hose with a trickle of water for 4-6 hours.', true),
('Barrel', 'https://luv2garden.com/wp-content/uploads/2020/08/How-to-Grow-and-Care-for-Barrel-Cactus-FB.jpg', 'Echinocactus', 'North and South America', 100, true, '10 feet', 'The Fishhook Barrel Cactus is often called the "Compass Barrel" because some of the larger plants lean toward the southwest.', 'From fall to spring, water infrequently (every month or two) and ensure that the soil drains completely. Do not leave any water in the tray or allow it to sit in water. In winter, simulate drought conditions, giving no water.', true),
('Star', 'https://www.cactus-online.net/wp-content/uploads/2022/10/SH8027-01.jpg', 'Astrophytum asterias', 'Rio Grande Valley of South Texas', 200, true, '3 inches', 'Only about 2,100 plants are known to exist in the wild.', 'Keep this cactus regularly watered (allowing it to dry out between waterings) and lightly fertilized during its growing season, and then repot it annually to allow more room for development. Star cactus can be grown outside only in climates with temperate, dry winters.', false),
('Old Lady', 'https://worldofsucculents.com/wp-content/uploads/2016/05/Mammillaria-hahniana-Old-Lady-Cactus2.jpg', 'Mammillaria hahniana', 'central Mexico', 20, true, '10 inches', 'the plant represents a succulent that grows well in either direct sun or partial shade', 'Most people will need to water Old lady cactus about every two weeks in summer and once a month in winter.', false),
('Gold Lace', 'https://i.etsystatic.com/9745001/r/il/4abdf2/842211355/il_570xN.842211355_avrb.jpg', 'Mammillaria elongata', 'central Mexico', 100, true, '8 inches', 'Also called lady finger cactus.', 'Water thoroughly when the soil is completely dry. When potted, water slowly, wait for water to flow out the bottom, and then pour the excess water from the tray to avoid water accumulation.', false),
('The Old Man', 'https://a-z-animals.com/media/2022/08/iStock-1295509893-683x1024.jpg', 'Cephalocereus senilis', 'central Mexico', 200, true, '50 feet', 'The flat-faced flowers are produced from a mass of long wool and bristles that cap the stem.', 'It enjoys well-draining soil and full sun, but prefers light afternoon shade. Bright sunlight encourages the growth of hair. Provide minimal to moderate water in the hot, summer months and almost no water at all during the winter months. It is hardy to minus ten degrees Fahrenheit.', false),
('Hedgehog', 'https://www.fs.usda.gov/wildflowers/plant-of-the-week/images/scarlethedgehogcactus/echinocereus_coccineus_3_lg.jpg', 'Echinocereus', 'central Mexico to the western United States', 10, true, '2 feet', 'It can produce over 20 stems and grows large vibrant flowers. These flowers are most commonly red and yellow in color.', 'These cacti need full sun, meaning at least six hours of direct sunlight on most days, to grow and flower their best. They can tolerate a bit of shade, but this can reduce flowering. When grown as a houseplant, place your Echinocereus cactus by your brightest window. A south-facing window is best.', true),
('Beehive', 'https://a-z-animals.com/media/2022/08/iStock-1315150606-694x1024.jpg', 'Coryphantha', 'North America and central Mexico', 5, true, '2 feet', 'Ariocarpus species contain sufficient alkaloids, principally hordenine, to make them mildly hallucinogenic.', 'Water thoroughly when the soil is completely dry. When potted, water slowly, wait for water to flow out the bottom, and then pour the excess water from the tray to avoid water accumulation.', false),
('African Milk Tree', 'https://www.bybrittanygoldwyn.com/wp-content/uploads/2020/10/Euphorbia-Trigonia-Care-5.jpg', 'Euphorbia trigona', 'Central Africa', 60, false, '9 feet', 'This plant is used ceremonially and is planted as part of some rituals.', 'Evenly water the top layer of soil and let it soak down, pour away any excess water. Increase watering in the summer while the plant is actively growing, check soil moisture once a week. In winter, only water once the top 1 inch of soil feels dry to the touch. Underwatering is always less harmful than overwatering.', false),
('Queen of the Night', 'https://www.gardenclinic.com.au/GC/media/GardenClinic/How%20to%20Grow/Articles/queen-of-the-night_shutterstock_227377960.jpg', 'Epiphyllum oxypetalum', 'rainforests of Central America', 30, true, '10 feet', 'It blooms once a year, only overnight. produces juicy edible fruits called : dragon fruit (Pitahaya)', 'Indirect sunlight is the best type of light for your queen of the night cactus flower to bloom. Indirect light occurs when an object diffuses sunlight.', true);
